# https://docs.datadoghq.com/tracing/trace_collection/open_standards/otel_collector_datadog_exporter/#receive-traces-from-localhost
receivers:
  otlp:
    protocols:
      http:

processors:
  batch:
  # See https://docs.datadoghq.com/tracing/trace_collection/open_standards/otel_collector_datadog_exporter/
  resource:
    attributes:
      - key: deployment.environment
        action: insert
        value: production
      - key: service.name
        action: insert
        value: datadog-otel-poc

exporters:
  datadog:
    api:
      site: datadoghq.com
      key: ${DD_API_KEY}

service:
  # telemetry:
  #   logs:
  #     level: 'debug'
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [datadog]
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [datadog]
